backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "mokaabtalayi-index"
    label: "Mokaab Talayi - Home"
    files:
      - file: "mokaabtalayi/index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }

  - name: "mokaabtalayi-threeLayer"
    label: "Mokaab Talayi - Three Layer"
    files:
      - file: "mokaabtalayi/pages/threelayer.html"
        label: "Three Layer Page"
        name: "threeLayer"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }

  - name: "mokaabtalayi-chapi"
    label: "Mokaab Talayi - Chapi"
    files:
      - file: "mokaabtalayi/pages/chapi.html"
        label: "Chapi Page"
        name: "chapi"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }

  - name: "mokaabtalayi-lamineti"
    label: "Mokaab Talayi - Lamineti"
    files:
      - file: "mokaabtalayi/pages/lamineti.html"
        label: "Lamineti Page"
        name: "lamineti"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
